config/routes.rb
HungryMan::Application.routes.draw do
  resources :categories

  resources :places

  root :to => "static_pages#home"
  get "static_pages/home"
  get "random_place/random"
  
  get "roulette_place/index"
  get "roulette_place/spin"
  get "roulette_place/AddCategory"
  get "roulette_place/clear"
  post "roulette_place/AddCategory"

  match 'spin', to: 'roulette_place#spin'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :address, :category, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/random_place_controller.rb
class RandomPlaceController < ApplicationController
  def random
    @places = Place.all
    @places = @places[rand(@places.length)]
    
    respond_to do |format|
      format.html
      format.json { render :json => @places }
    end
  end
end

app/controllers/roulette_place_controller.rb
class RoulettePlaceController < ApplicationController
  def spin
    @places = Place.where("category in (?)", session[:category].keys)
    @place = @places[rand(@places.length)]
    respond_to do |format|
      format.html
      format.json { render :json => @place }
    end
  end

  def index
    if (session[:category] == nil)
      c = Hash.new
    else
      c = session[:category]
    end
    @places = Place.where("category in (?)", c.keys)
    
    respond_to do |format|
      format.html
      format.json { render :json => @places }
    end
  end

  def AddCategory
    h = session[:category].nil? ? Hash.new : session[:category]
    h[params[:category]] = 1
    session[:category] = h
  end

  def AddPlace
  end
  def Create
  end
  def clear
    session[:category] = nil
    redirect_to "/roulette_place/index"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/random_place_helper.rb
module RandomPlaceHelper
end

app/helpers/roulette_place_helper.rb
module RoulettePlaceHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  <div class="container">
    <nav>
      <ul class="nav pull-right">
        <li><%= link_to "Home",  '/' %></li>
	<li><%= link_to "Places",  '/places' %></li>
	<li><%= link_to "Random",  '/random_place/random' %></li>
	<li><%= link_to "Roulette",  '/roulette_place/index' %></li>
      </ul>
    </nav>
  </div>
  </div>
      <script>
        var require = {
	        baseUrl: 'bonsai-master/src/',
	        urlArgs: '?' + +(new Date)
        };
      </script>
      <script type="text/javascript" src="bonsai-master/lib/requirejs/require.js"></script>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hungry Man</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="center hero-unit">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </div>



</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.name %></td>
    <td><%= place.category %></td>
    <td><%= place.address %></td>
    <td><%= link_to 'Show', place %></td>
    <td><%= link_to 'Edit', edit_place_path(place) %></td>
    <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @place.name %>
</p>

<p>
  <b>Category:</b>
  <%= @place.category %>
</p>

<p>
  <b>Address:</b>
  <%= @place.address %>
</p>


<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/random_place/random.html.erb
<div class="center hero-unit">
<h1>Your random restraunt:</h1>
  <p>
    <%= @places.name %><BR>
    <%= @places.address %>
  </p>
</div>

app/views/roulette_place/AddCategory.html.erb
<%= form_tag(:method => "post") do %>
  <%= label_tag(:category, "category:") %>
  <%= text_field_tag(:category) %>
  <%= submit_tag("Add Category") %>
<% end %>

app/views/roulette_place/index.html.erb
<h1>Listing places</h1>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Address</th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.name %></td>
    <td><%= place.category %></td>
    <td><%= place.address %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to 'Spin', '/roulette_place/spin' %> || 
<%= link_to 'Add Category', '/roulette_place/AddCategory' %>

app/views/roulette_place/spin.html.erb
<h1>Spin</h1>
<P>
  <%= @place.name %><BR>
</P>

    <section id="bonsai-api">
      <div class="stage"></div>
      <div class="editor">
    <script type="text/javascript">

      var rectWidth = 100;
      var rectHeight = 50;
      var rectX = 25;
      var rectY = 50;
      var r = 45;

      var lineTo = {
        x : rectX + rectWidth - r, //100
        y : rectY // 50
      };

      // **********************************************************************
      // bonsai api

      require(['bonsai'], function(bs){
        console.log('Bonsai loaded:', bs);

        // create stage
        var stage = new bs.Stage(document.querySelector('#bonsai-api div'), 150, 150);

        var arcto = new bs.Path([
          'M', rectX, ',', rectY,
          'L', rectX + rectWidth - r, ',', lineTo.y
        ].join(' ')).attributes({stroke:'yellow', 'stroke-width':5});
        arcto.canvasArcTo(rectX + rectWidth/*125*/, rectY/*50*/, rectX + rectWidth/*125*/, rectY + r/*75*/, r/*25*/);
        arcto.lineTo(rectX + rectWidth, rectY + rectHeight);
        stage.addChild(arcto);
      });

      // **********************************************************************
      // canvas api

      // create stage
      var stage = document.querySelector('#canvas-api canvas').getContext('2d');
      stage.beginPath();
      stage.moveTo(rectX, rectY);
      stage.lineTo(rectX + rectWidth - r /*100*/, lineTo.y/*50*/);
      stage.arcTo(rectX + rectWidth/*125*/, rectY/*50*/, rectX + rectWidth/*125*/,
          rectY + r/*75*/, r/*25*/);
      stage.lineTo(rectX + rectWidth, rectY + rectHeight);
      stage.strokeStyle = 'red';
      stage.strokeWidth = 5;
      stage.stroke();

      // **********************************************************************
      //
      // svg api

      var stage = document.querySelector('#svg-api div');
      stage.innerHTML = '<svg><path d="'+[
        'M',rectX,',',rectY,
        'L',rectX+rectWidth-r,',',rectY,
        'A',r,',',r,',',0,',',0,',',1,',',rectX+rectWidth,',',rectY+r,
        'L',rectX + rectWidth, rectY + rectHeight
      ].join(' ')+'" style="stroke:red; stroke-width:5px;" /></svg>';

      // **********************************************************************
      // raphaeljs api

      // **********************************************************************
      // easeljs api

      // **********************************************************************
      // paperjs api

    </script>
      </div>
    </section>

app/views/static_pages/home.html.erb
<h1>Home</h1>
  <p>
    Here we are to write some stuff about some stuff describing some more stuff.
  </p>